services:
  - type: web
    name: breastscan-upload
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1